#ifndef SERIAL_H
#define SERIAL_H

#include <stdint.h>

typedef enum DeviceError {
    DEVICEERR_OK = 0,
    DEVICEERR_NOTCART,
    DEVICEERR_USBBUSY,
    DEVICEERR_NODEVICES,
    DEVICEERR_CARTFINDFAIL,
    DEVICEERR_CANTOPEN,
    DEVICEERR_FILEREADFAIL,
    DEVICEERR_RESETFAIL,
    DEVICEERR_RESETPORTFAIL,
    DEVICEERR_TIMEOUTSETFAIL,
    DEVICEERR_PURGEFAIL,
    DEVICEERR_READFAIL,
    DEVICEERR_WRITEFAIL,
    DEVICEERR_WRITEZERO,
    DEVICEERR_CLOSEFAIL,
    DEVICEERR_BITMODEFAIL_RESET,
    DEVICEERR_BITMODEFAIL_SYNCFIFO,
    DEVICEERR_SETDTRFAIL,
    DEVICEERR_CLEARDTRFAIL,
    DEVICEERR_GETMODEMSTATUSFAIL,
    DEVICEERR_TXREPLYMISMATCH,
    DEVICEERR_READCOMPSIGFAIL,
    DEVICEERR_NOCOMPSIG,
    DEVICEERR_READPACKSIZEFAIL,
    DEVICEERR_BADPACKSIZE,
    DEVICEERR_MALLOCFAIL,
    DEVICEERR_UPLOADCANCELLED,
    DEVICEERR_TIMEOUT,
    DEVICEERR_POLLFAIL,
    DEVICEERR_DATATOOBIG,
    DEVICEERR_CMDFAIL,
    DEVICEERR_COMMFAIL,
} DeviceError;

typedef enum DataType {
    DATATYPE_UNKNOWN,
    DATATYPE_TEXT,
    DATATYPE_RAWBINARY,
    DATATYPE_HEADER,
    DATATYPE_SCREENSHOT,
    DATATYPE_HEARTBEAT,
    DATATYPE_RDBPACKET,
    DATATYPE_HANDSHAKE,
    DATATYPE_INGAME_STATE,
    DATATYPE_SAVE_FILENAME,
} DataType;

#endif