#ifndef TEXTURES_H
#define TEXTURES_H

#include "z64.h"
#include "util.h"

typedef enum TextureId {
    TEXTURE_ID_NONE,

    TEXTURE_ID_POT_GOLD = 1,
    TEXTURE_ID_POT_KEY = 2,
    TEXTURE_ID_POT_BOSSKEY = 3,
    TEXTURE_ID_POT_SKULL = 4,

    TEXTURE_ID_CRATE_DEFAULT = 5,
    TEXTURE_ID_CRATE_GOLD = 6,
    TEXTURE_ID_CRATE_KEY = 7,
    TEXTURE_ID_CRATE_SKULL = 8,
    TEXTURE_ID_CRATE_BOSSKEY = 9,

    TEXTURE_ID_SMALLCRATE_GOLD = 10,
    TEXTURE_ID_SMALLCRATE_KEY = 11,
    TEXTURE_ID_SMALLCRATE_SKULL = 12,
    TEXTURE_ID_SMALLCRATE_BOSSKEY = 13,

    TEXTURE_ID_BEEHIVE_GOLD = 14,
    TEXTURE_ID_BEEHIVE_KEY = 15,
    TEXTURE_ID_BEEHIVE_SKULL = 16,
    TEXTURE_ID_BEEHIVE_BOSSKEY = 17,

    TEXTURE_ID_CHEST_FRONT_GILDED = 18,
    TEXTURE_ID_CHEST_BASE_GILDED = 19,
    TEXTURE_ID_CHEST_FRONT_SILVER = 20,
    TEXTURE_ID_CHEST_BASE_SILVER = 21,
    TEXTURE_ID_CHEST_FRONT_SKULL = 22,
    TEXTURE_ID_CHEST_BASE_SKULL = 23,

    TEXTURE_ID_CHEST_FRONT_HEART = 24,
    TEXTURE_ID_CHEST_BASE_HEART = 25,
    TEXTURE_ID_POT_SIDE_HEART = 26,
    TEXTURE_ID_POT_TOP_HEART = 27,
    TEXTURE_ID_CRATE_HEART = 28,
    TEXTURE_ID_SMALLCRATE_HEART = 29,
    TEXTURE_ID_BEEHIVE_HEART = 30,

    TEXTURE_ID_GRASS_CUSTOM = 31,
    TEXTURE_ID_GRASS_SMALL_CUSTOM = 32,

    TEXTURE_ID_MAX,
} TextureId;

#define PTMC_OFF       0
#define PTMC_CONTENTS  1
#define PTMC_UNCHECKED 2

uint8_t* get_texture(TextureId textureID);
void init_textures();

#endif
